name: Run Django Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        ports:
          - $POSTGRES_PORT:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Databse
      run: |
        chmod +x ./docker/general/wait_for_database.sh
        /bin/bash ./docker/general/wait_for_database.sh

    - name: Run Django Tests
      run: |
        python manage.py test
